name: 'cross-gem'
description: 'Cross compiles a native Ruby gem written in Rust'
author: 'oxidize-rs'
branding:
  icon: 'chevron-right'
  color: 'gray-dark'
inputs:
  platform:
    required: true
    description: 'The target Ruby platform'
  directory:
    description: 'Directory of gem to build'
  ruby-versions:
    description: 'Comma seperated list of Ruby versions to build for'
    default: '3.2, 3.1, 3.0, 2.7, 2.6, 2.5, 2.4, 2.3'
  command:
    description: 'Command to build gem inside of container'
  setup:
    description: 'Extra setup script to run inside container'
  artifact-name:
    description: 'Name of the uploaded artifact'
    default: 'cross-gem'
  version:
    description: 'Docker version tag for container (corresponds to rb-sys version)'
    default: "latest"
  env:
    description: 'Extra env vars to set when compiling'
  use-ruby-linker-for-cargo:
    description: 'Set the CARGO_TARGET_{TARGET}_LINKER to use the linker from RbConfig'
runs:
  using: 'node16'
  main: 'dist/index.js'
