name: 'cross-gem'
icon: chevron-right
color: gray-dark
description: 'Cross compiles a native Ruby gem written in Rust'
author: 'oxidize-rs'
inputs:
  platform:
    required: true
    description: 'The target Ruby platform'
  directory:
    description: 'Directory of gem to build'
  command:
    description: 'Command to build gem inside of container'
  env:
    description: 'Extra env vars to set when compiling'
runs:
  using: 'node16'
  main: 'dist/index.js'
